TK_ECAR/Controllers/CategoriasPreguntasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TK_ECAR.Application_Services;
using TK_ECAR.Models;

namespace TK_ECAR.Controllers
{
    public class CategoriasPreguntasController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult NuevaCategoriaPreguntas()
        {
            CategoriasPreguntasModel categorias = new CategoriasPreguntasModel();
            categorias.Accion = Framework.EnumAccionEntity.Alta;
            categorias.Ordenacion = new CategoriasPreguntasService().OrdenacionCategoriasPreguntas(Framework.EnumAccionEntity.Alta).Count();
            return PartialView("_MantenimientoCategoriasPreguntas", categorias);
        }

        public ActionResult EditarCategoriaPreguntas(int idCategoria)
        {

            CategoriasPreguntasService serviceCategorias = new CategoriasPreguntasService();
            var categoria = serviceCategorias.GetCategoriaPregunta((int?)idCategoria);
            categoria.Accion = Framework.EnumAccionEntity.Modificacion;

            return PartialView("_MantenimientoCategoriasPreguntas", categoria);
        }

        public ActionResult BorraCategoriaPregunta(int idCategoria)
        {

            CategoriasPreguntasService serviceCategorias = new CategoriasPreguntasService();
            serviceCategorias.BorrarCategoria(idCategoria);

            return Json("Success", JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetPreguntasByCategoriaJson(int categoriaPregunta)
        {
            List<int> categorias = new List<int> { categoriaPregunta };

            var preguntas = new PreguntasService().GetPreguntasByCategoria(categorias, null);

            var data = new
            {
                data = preguntas,
                draw = 1,
                recordsFiltered = preguntas.Count,
                recordsTotal = preguntas.Count
            };

            return Json(data, JsonRequestBehavior.AllowGet);
        }



        [ActionName("GuardarCategoriasPreguntas")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GuardarCategoriaPreguntas(CategoriasPreguntasModel modelo)
        {
            CategoriasPreguntasService serviceCategorias = new CategoriasPreguntasService();

            if (modelo.Accion == Framework.EnumAccionEntity.Alta || modelo.Accion == Framework.EnumAccionEntity.Modificacion)
            {
                serviceCategorias.SaveCategoriasPreguntas(modelo);
            }

            return Json("Success", JsonRequestBehavior.AllowGet);
        }


        #region CargaDatatable
        public ActionResult CategoriasPreguntasJson()
        {
            var categorias = new CategoriasPreguntasService().GetCategoriasPreguntasDatatable(UserModel.Empresas.ToList());

            var data = new
            {
                data = categorias,
                draw = 1,
                recordsFiltered = categorias.Count,
                recordsTotal = categorias.Count
            };

            return Json(data, JsonRequestBehavior.AllowGet);
        }
        #endregion  
    }
}

TK_ECAR/Views/CategoriasPreguntas/Index.cshtml
@using resourceView = TK_ECAR.Content.resources
@*@model IEnumerable<TK_ECAR.Models.CategoriasDataTableModel>*@
@using System.Configuration;

<div class="row">
    <div class="col-sm-12">
        <div class="infoCategGestion">
            @{
                var actionLink = Ajax.ActionLink("JSTITLEMODAL", "NuevaCategoriaPreguntas", "CategoriasPreguntas", new { },
                new AjaxOptions
                {
                    UpdateTargetId = "modalbodyCategoriasPreguntas",
                    OnSuccess = "showModalCategoriasPreguntas();",
                    OnComplete = "completeModal()",
                    InsertionMode = InsertionMode.Replace,
                    OnBegin = "setTitleModal('JSTITLEMODAL')"
                }, new { @title = "tooltip", @class = "tk-icon-med icon-tk-plus", @style = "float: right;" }).ToString();
            }
            @*<h3>@resourceView.TitleCategorias    @Html.Raw(actionLink.Replace("JSTITLEMODAL", @resourceView.LNuevaCategoria))</h3>*@
            <h3>@resourceView.TK_ECAR_Resource.TitleCategoriasPreguntas
                <span id="linkuser" style="float: right;">@resourceView.TK_ECAR_Resource.LAñadir</span> 
                @Html.Raw(actionLink.Replace("JSTITLEMODAL", @resourceView.TK_ECAR_Resource.LNuevaCategoria).Replace("tooltip", @resourceView.TK_ECAR_Resource.LNuevaCategoria))
            </h3>
            <p>@resourceView.TK_ECAR_Resource.TitleCategoriasInf</p>
        </div>
    </div>
</div>

@*
    @{
        var actionLinkEdit = Ajax.ActionLink("JSTITLEACTION", "EditarCategoria", "Categorias", new { idDocumentacion = "JSVARTIPO" },
        new AjaxOptions
        {
            UpdateTargetId = "modalbodyCategorias",
            OnSuccess = "showModalCategorias();",
            OnComplete = "completeModal()",
            InsertionMode = InsertionMode.Replace,
            OnBegin = "setTitleModal('JSTITLEMODAL')"
        }).ToString();
    }
*@

<table id="tableCategoriasPreguntas" class="display responsive" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>ID_Categoria</th>
            <th>@resourceView.ModelsResources.lblEmpresa</th>
            <th>@resourceView.TK_ECAR_Resource.CategoriasCabOrdenacion</th>
            <th>@resourceView.TK_ECAR_Resource.GeneralCabDescripcion</th>
            <th>@resourceView.TK_ECAR_Resource.DataTableCabAccion</th>
            @*<th>@resourceView.TK_ECAR_Resource.DataTableBaja</th>*@
            <th>DescEmpresa</th>
        </tr>
    </thead>
    <tbody>
        @*@foreach (var item in Model)
        {
        <tr>
            <td>
                <img src="~/Content/img/Application/details_open.png"
                     rel="@item.Descripcion" alt="expand/collapse">
            </td>
            <td>@item.ID_Categoria</td>
            <td>@item.ID_Documento</td>
            <td>@item.Ruta</td>
            <td>@item.DescCategoria</td>
            <td>@item.Nombre</td>
            <td>
                <span></span> @Html.Raw(actionLinkEdit.Replace("JSVARTIPO", (item.ID_Categoria).ToString()).Replace("JSTITLEACTION", @resourceView.AccionEditar).Replace("JSTITLEMODAL", @resourceView.TitleCategoriaEditar))
            </td>
        </tr>
    }*@
    </tbody>

</table>

@Html.Partial("_ModalCategoriasPreguntas")

@section Scripts {

    <link rel="stylesheet" type="text/css" href='@Styles.Url("~/Content/dataTablecss")'>
    <link rel="stylesheet" type="text/css" href='@Styles.Url("~/Content/dataTablecssResponsive")'>
    
    <script src='@Scripts.Url("~/bundles/datatable")'> </script>
    <script src='@Scripts.Url("~/bundles/dtresponsive")'> </script>

    <script type="text/javascript">
        var _tableCategoriasPreguntas;

        var actionCategoria = '@Ajax.RawActionLink("textoQuitarPorVacio", "EditarCategoriaPreguntas", "CategoriasPreguntas", new { idCategoria = "valordelidaccion" },
        new AjaxOptions { UpdateTargetId = "modalbodyCategoriasPreguntas", OnSuccess = "showModalCategoriasPreguntas();", OnComplete = "completeModal()", InsertionMode = InsertionMode.Replace },
        new { @data_toggle = "popover", @data_placement = "top", @data_trigger = "hover", @data_content = "accionmenu" })';
        actionCategoria = actionCategoria.replace("textoQuitarPorVacio", "");

        $(document).ready(function () {
            _tableCategoriasPreguntas = $('#tableCategoriasPreguntas').DataTable(
                {
                    "ordering": true,
                    "processing": true,
                    "paginate": true,
                    "order": [[2, "asc"]],
                    "ajax": {
                        "url": '@Url.Action("CategoriasPreguntasJson", "CategoriasPreguntas")',
                        "datatype": "json",
                        "type": "POST"

                    },
                    "columns": [
                        { "data": "ID_Categoria" },
                        { "data": "ID_Empresa" },
                        { "data": "Ordenacion" },
                        { "data": "Nombre" },
                        { "data": "AccionDatatable" },
                        //{ "data": "Baja" },
                        { "data": "DescEmpresa" },
                    ],
                    "language": {
                        "url": '@Url.Content(ConfigurationManager.AppSettings["baseUrl"] + "/Content/DataTables/i18n/" + @resourceView.TK_ECAR_Resource.ArchivoIdiomaDataTable )'
                    },
                    "drawCallback": function () {
                        $('[data-toggle="popover"]').popover({ html: true });
                    },
                    "columnDefs": [
                    {
                        "targets": [0, 5],
                        "visible": false,
                        "searchable": false
                        //,
                        //"mRender": function ( data, type, row ) {
                        //    return '<img src="/Content/img/Application/details_open.png" rel="' + row.Respuesta + '" alt="expand/collapse">';}
                    },
                    {
                        "targets": 2,
                        "width": "2%",
                    },
                    {
                        "targets": 1,
                        "width": "2%",
                        "render": function (data, type, row) {
                            return "<a data-placement='right' data-toggle='popover' data-trigger='hover' data-content='" + row.DescEmpresa + "' >" + row.ID_Empresa + "</a>";
                        }

                    },
                    {
                        "targets": 3,
                        "width": "70%",
                    },
                    {
                        "targets": 4,
                        "orderable": false,
                        "searchable": false,
                        "className": "dt-center",
                        "type": "html",
                        "render": function (data, type, row) {
                            var menuAcciones = "";
                            menuAcciones = menuAcciones + "<a class='tk-icon-med icon-tk-edit tk-icon-bold ' "
                                            + actionCategoria.replace("valordelidaccion", row.ID_Categoria)
                                            .replace("TITTLEACCION", '@resourceView.TK_ECAR_Resource.AccionEditar')
                                            .replace("accionmenu", "@resourceView.TK_ECAR_Resource.AccionEditar") + " </a>";
                            menuAcciones = menuAcciones + "<a class='tk-icon-med icon-tk-delete tk-icon-bold tk-icon-red ' "
                                            +  "href='#' onclick='return clickBorrar(event," + row.ID_Categoria + ");' "
                                            + " data-toggle = 'popover', data-placement = 'top', data-trigger = 'hover' "
                                            + "data-content = '@Html.Raw(@resourceView.TK_ECAR_Resource.AccionBorrar)'>"
                                            + "</a>";

                            return menuAcciones;

                            @*var actionCategoria = '@Ajax.RawActionLink("<span>TITTLEACCION</span>", "EditarCategoriaPreguntas", "CategoriasPreguntas", new { idCategoria = "valordelidaccion" },
                            new AjaxOptions { UpdateTargetId = "modalbodyCategoriasPreguntas", OnSuccess = "showModalCategoriasPreguntas();", OnComplete = "completeModal()", InsertionMode = InsertionMode.Replace }, new { @class = "" })';
                            actionCategoria = actionCategoria.replace("valordelidaccion", row.ID_Categoria); //Reemplazar valordelidaccion por el valor de row.columna
                            actionCategoria = actionCategoria.replace("TITTLEACCION", '@resourceView.TK_ECAR_Resource.AccionEditar'); //Reemplazar TITTLEACCION por el valor de row.columna
                            return actionCategoria;*@
                        }
                    },
                    //{
                    //    "targets": 5,
                    //    "orderable": false,
                    //    "type": "html",
                    //    "render": function (data, type, row) {
                    //        return syntaxLinkBaja(data, row);
                    //    }
                    //},
                    ]
                });
        });

        function syntaxLinkBaja(data, row) {
            return "<a class='tk-icon icon-tk-delete tk-icon-bold tk-icon-red' href='#' onclick='return clickBorrar(event," + row.ID_Categoria + ");'></a>";
        }

        function clickBorrar(e, numCategoria) {
            e.preventDefault();

            var numPreguntasInCategoria = 0;

            var linkCategorias = '@Html.Raw(Url.Action("GetPreguntasByCategoriaJson", "CategoriasPreguntas", new { categoriaPregunta = "idborrar" }))';
            linkCategorias = linkCategorias.replace("idborrar", numCategoria);
            $.ajax({
                "url": linkCategorias,
                "async": false,
                "dataType": 'json',
                "success": function (data, t, x) {
                    numPreguntasInCategoria = data.data.length;
                }
            });

            var pregunta = '@resourceView.TK_ECAR_Resource.msgPreguntaBorrarCategoria';
            if (numPreguntasInCategoria > 0) {
                pregunta = pregunta + '</br></br>'
                pregunta = pregunta + '<p>' + '@resourceView.TK_ECAR_Resource.preguntaBorrarCategoriaPregunta1' + " </p>";
                pregunta = pregunta + '<p>' + '@resourceView.TK_ECAR_Resource.preguntaBorrarCategoriaPregunta2' + "</p>";
                pregunta = pregunta.replace("numeropreguntas", numPreguntasInCategoria);
            }
            confirm('@resourceView.TK_ECAR_Resource.msgBorrarCategoria', pregunta,
                function (result) {
                    if (result) {
                        var link = '@Html.Raw(Url.Action("BorraCategoriaPregunta", "CategoriasPreguntas", new { idCategoria = "idborrar" }))';
                        link = link.replace("idborrar", numCategoria);
                        $.ajax({
                            "url": link,
                            "dataType": 'json',
                            "success": function (data, t, x) {
                                reloadTablecategoriasPreguntas();
                            }
                        });
                        //_tableCategorias.rows.draw();
                    }
                });
        }

        function reloadTablecategoriasPreguntas() {
            _tableCategoriasPreguntas.ajax.reload(null, false);
        }

        function showModalCategoriasPreguntas() {
            $('#modalCategoriasPreguntas').modal('show');
        }
        function setTitleModal(title) {
            $('#modaltitleCategoriasPreguntas').text(title);
        }

        //function completeModal() {
        //    //para que funcione los validadores a la viewpartial recien creada.
        //    //reconstruye el DOM con los validadores de los campos nuevos
        //    $("form").removeData("validator");
        //    $("form").removeData("unobtrusiveValidation");
        //    $.validator.unobtrusive.parse("form");
        //    $("form").validate();
        //}

    </script>
}

TK_ECAR/Views/CategoriasPreguntas/_MantenimientoCategoriasPreguntas.cshtml
@using TK_ECAR.Models
@model CategoriasPreguntasModel

@Html.HiddenFor(m => m.ID_Categoria)
@Html.HiddenFor(m => m.Accion)
<div class="form-horizontal">
    <div class="form-group">
        @Html.RequiredLabelFor(m => m.ID_Empresa, new { @class = "control-label col-sm-4" })
        <div class="col-sm-8">
            @Html.DropDownListEmpresas("ID_Empresa", new { @class = "form-control" }, Model.ID_Empresa, Model.Accion)
        </div>
    </div>    
    <div class="form-group">
        @Html.RequiredLabelFor(m => m.Nombre, new { @class = "control-label col-sm-4" })
        <div class="col-sm-8">
            @Html.TextBoxFor(m=>m.Nombre, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.RequiredLabelFor(m => m.Ordenacion, new { @class = "control-label col-sm-4" })
        <div class="col-sm-8">
            @Html.DropDownListOrdenacionCategoriasPreguntas("Ordenacion", new { @class = "form-control" }, Model.Ordenacion, Model.Accion)
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-12">
            @Html.Partial("_CustomValidationSummary", ViewData.ModelState)
        </div>
    </div>
</div>

 

TK_ECAR/Views/CategoriasPreguntas/_ModalCategoriasPreguntas.cshtml
@using resourceView = TK_ECAR.Content.resources.TK_ECAR_Resource


@using (Html.BeginForm("GuardarCategoriasPreguntas", "CategoriasPreguntas", null, FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "stripHtml('formCategoriasPreguntas')", @id= "formCategoriasPreguntas" }))
{ @Html.AntiForgeryToken()
    
        <div class="modal fade" id="modalCategoriasPreguntas" role="dialog">
            <div class="vertical-alignment-helper">
                <div class="modal-dialog  vertical-align-center">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                <span class="modal-header-logo"></span>
                            </button>
                            <h4 class="modal-title" id="modaltitleCategoriasPreguntas"> </h4>
                        </div>
                         
                        <div class="modal-body"> 
                            @*<div id="toast-container"></div>*@              
                            <div id="modalbodyCategoriasPreguntas"></div> 
                            
                        </div>                             
                        <div class="modal-footer">
                            <button type="submit" id="aceptarCategoriasPreguntas" class="btn btn-default">@resourceView.AccionAceptar</button>
                            <button type="button" class="btn btn-cancel" data-dismiss="modal">@resourceView.AccionCerrar</button>
                         </div>

                    </div>
                </div>
            </div>
        </div>
      
}

    <script type="text/javascript">


        $(document).ready(function () {

            $("#formCategoriasPreguntas").submit(function (e) {


                if ($("#formCategoriasPreguntas").valid()) {//validamos el form
                    var formData = new FormData(this);
                    @*var uRl = '@Url.Action("Index", "CategoriasPreguntas")';*@
                    $.ajax({
                        type: this.method,
                        url: this.action ,
                        data: formData,
                        contentType: false,
                        processData: false,

                        success: function (data) {
                            ajaxSuccessCategoriasPreguntas();
                            reloadTablecategoriasPreguntas();
                            //setTimeout(function () { window.location.replace(uRl) }, 1000);
                            
                        },
                        error: function (error) {
                            ajaxErrorCategoriasPreguntas();
                        }
                    });
                }

                e.preventDefault();

            });
        });

        function ajaxSuccessCategoriasPreguntas() {

            notify('@resourceView.toastrInfCategoriaCorrecta', 'i');
            @*toastr["info"]("@resourceView.toastrInfCategoriaCorrecta");*@
            $('#modalCategoriasPreguntas').modal('hide');
        }
        function ajaxErrorCategoriasPreguntas() {

            notify('@resourceView.toastrInfCategoriaError', 'e');
            @*toastr["error"]("@resourceView.toastrInfCategoriaError");*@

        }


    </script>