TK_ECAR/Controllers/MiVehiculoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TK_ECAR.Models;
using TK_ECAR.Application_Services;
using System.IO;
using TK_ECAR.Utils;
using TK_ECAR.Framework;

namespace TK_ECAR.Controllers
{
    public class MiVehiculoController : BaseController
    {
        public ActionResult Index()
        {
            DatosVehiculoModel datosVista = new DatosVehiculoModel();
            string Matricula = new MiVehiculoService().GetMatriculaVehiculoActivo(UserModel.Dni); //40965660-S

            if (!string.IsNullOrEmpty(Matricula))
            {
                var miVehiculo = new FlotaService().GetDatosVehiculo(Matricula);
                datosVista = miVehiculo;
            }

            ViewData["Matricula"] = Matricula;

            return View(datosVista);
        }

        public PartialViewResult VerVehiculo(string matricula)
        {

            ViewBag.FichaConductor = false;

            var miVehiculo = new FlotaService().GetDatosVehiculo(matricula);

            ViewData["Matricula"] = matricula;
            ViewData["Sociedad"] = miVehiculo.DatosGenerales_Vehiculo.Empresa;

            return  PartialView("_Vehiculo", miVehiculo) ;
        }

        #region DocumentosVehiculo
        public ActionResult NuevoDocumentoVehiculo(string matricula)
        {
            DatosVehiculoDocumentacionModel documentacionVehiculo = new DatosVehiculoDocumentacionModel();
            documentacionVehiculo.Matricula = matricula;
            return PartialView("_DocumentacionVehiculoAlta", documentacionVehiculo);
        }

        public FileResult DowmnLoadDocumentoVehiculo(int idDocumento, string matricula, int idAlerta, int idCatergoria)
        {
            string fileToDownload = string.Empty;
            if (idCatergoria == (int)EnumTipoAlerta.ITV)
            {
                var documento = new VehiculoService().GetListDatosITV_ECAR(matricula).Where(x=> x.ID == idDocumento).FirstOrDefault();
                fileToDownload = $"{Global.PathToUploadDocumentITV}{matricula}/{documento.Documento}";
            }
            else if (idAlerta == 0)
            {
                var documentos = new FlotaService().GetDatosDocumentacionVehiculo(idDocumento, matricula);
                fileToDownload = Global.GetPathToUploadDocumentMiVehiculo(matricula, "-", "_") + documentos.Documento;
            }
            else
            {
                var alerta = new AlertasService().GetAlerta(idAlerta);
                fileToDownload = Global.PathToUploadDocumentAlertas + idAlerta.ToString() + "/" + alerta.Fichero;
            }

            //byte[] fileBytes = System.IO.File.ReadAllBytes(@documentos.Ruta);

            return File(System.Web.HttpContext.Current.Server.MapPath(fileToDownload), System.Net.Mime.MediaTypeNames.Application.Octet, Path.GetFileName(System.Web.HttpContext.Current.Server.MapPath(fileToDownload)));
        }

        public ActionResult CompruebaDocumentoVehiculo(string nombreArchivo, string matricula)
        {
            bool valorReturn = false;

            valorReturn = FileUtilities.ExisteDocumentoToUploadEnDisco(Global.GetPathToUploadDocumentMiVehiculo(matricula, "-", "_") + nombreArchivo);


            return Json(valorReturn, JsonRequestBehavior.AllowGet);
        }

        #region mantenimiento documentación
        [HttpPost]
        public ActionResult BorrarDocumentoVehiculo(int idDocumento, string matricula)
        {
            FlotaService flota = new FlotaService();

            flota.DeleteDocumentacion(idDocumento, matricula);

            return Json("Success");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GrabaDocumentoVehiculo(DatosVehiculoDocumentacionModel modelo)
        {
            
            FlotaService flota = new FlotaService();
            
            flota.SaveDocumentacionVehiculo(modelo);

            return Json("Success", JsonRequestBehavior.AllowGet);

            //var miflota = new List<DatosVehiculoDocumentacionModel>();

            //miflota = flota.GetDatosVehiculoDocumentacion(modelo.Matricula).ToList();

            //return Json(data, JsonRequestBehavior.AllowGet);
        }
        #endregion
        #endregion

        #region imagen carnet conducir
        public ActionResult GetImgCarnetConducir(string nombreArchivo, int idAlerta)
        {
            FileStream fs = null;

            var archivoCarnet = Global.PathToUploadDocumentAlertas + idAlerta.ToString() + "/" + nombreArchivo;

            try
            {
                fs = new FileStream(System.Web.HttpContext.Current.Server.MapPath(archivoCarnet), FileMode.Open, FileAccess.Read);
            }

            catch
            {
                fs = new FileStream(System.Web.HttpContext.Current.Server.MapPath("~/Content/img/Application/CarnetConducirVacio.jpg"), FileMode.Open, FileAccess.Read);
            }
            return File(fs, "image/jpeg");
        }
        #endregion

        #region CargaDatatable
        public ActionResult DocumentacionVehiculoJson(string matricula)
        {
            var miflota = new FlotaService().GetDatosVehiculoDocumentacion(matricula).ToList();

            var data = new
            {
                data = miflota,
                draw = 1,
                recordsFiltered = miflota.Count,
                recordsTotal = miflota.Count
            };

            return Json(data, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region CargaDatatable
        public ActionResult ConductorJson(string matricula)
        {
            var datos = new FlotaService().GetDatosConductoresVehiculo(matricula).ListaConductores;

            var data = new
            {
                data = datos,
                draw = 1,
                recordsFiltered = datos.Count,
                recordsTotal = datos.Count
            };

            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SOLREDJson(string matricula)
        {
            var datos = new FlotaService().GetDatosVehiculoConsumoCombustible(matricula).ToList();

            var data = new
            {
                data = datos,
                draw = 1,
                recordsFiltered = datos.Count,
                recordsTotal = datos.Count
            };

            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult MultasJson(string matricula)
        {
            var datos = new FlotaService().GetDatosVehiculoMultas(matricula).ToList();

            var data = new
            {
                data = datos,
                draw = 1,
                recordsFiltered = datos.Count,
                recordsTotal = datos.Count
            };

            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult RentingJson(string matricula)
        {
            var datos = new FlotaService().GetDatosVehiculoLeasePlan(matricula).ToList();

            var data = new
            {
                data = datos,
                draw = 1,
                recordsFiltered = datos.Count,
                recordsTotal = datos.Count
            };

            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ViaVerdeJson(string matricula)
        {
            var datos = new FlotaService().GetViaVerdeDataTableByMatricula(matricula).LineasDataTable;

            if (datos == null)
            {
                datos = new List<ViaVerdeLineaDatatable>();
            }

            var data = new
            {
                data = datos,
                draw = 1,
                recordsFiltered = datos.Count,
                recordsTotal = datos.Count
            };

            return Json(data, JsonRequestBehavior.AllowGet);
        }


        #endregion

    }
}

TK_ECAR/Views/MiVehiculo/_Conductor.cshtml
@using resourceView = TK_ECAR.Content.resources.TK_ECAR_Resource
@using TK_ECAR.Models
@model ConductoresVehiculoModel

@{ 
    //var imagePathCarnetVacio = "img/Application/CarnetConducirVacio.jpg";
    var VerFichaConductor = false;
    if (ViewBag.FichaConductor != null)
    {
        VerFichaConductor = ViewBag.FichaConductor;
    }

}

<br>
@*<ul id="tab_Conductor" class="nav nav-tabs">
    <li><a href="#fichaConductor" data-toggle="tab">@resourceView.TabDatosConductor</a></li>
    <li><a href="#carnet" data-toggle="tab">@resourceView.TabCarnet</a></li>
</ul>*@

@*<div class="tab-content">
    <div id="fichaConductor" class="tab-pane fade in active">*@
<div class="notice notice-Lightgreen">
    <div class="row">
        <div class="col-sm-3">
            <strong>@Html.LabelFor(model => model.NumEmpleado)</strong>
            <p>@Html.DisplayFor(model => model.NumEmpleado)</p>
        </div>
        <div class="col-sm-3">
            <strong>@Html.LabelFor(model => model.NombreCompleto)</strong>
            <p>@Html.DisplayFor(model => model.NombreCompleto)</p>
        </div>

        <div class="col-sm-3">
            <strong>@Html.LabelFor(model => model.DNI)</strong>
            <p>@Html.DisplayFor(model => model.DNI)</p>
        </div>
        <div class="col-sm-2">
            <strong>@Html.LabelFor(model => model.FechaVtoCarnet)</strong>
            <p>@Html.DisplayFor(model => model.FechaVtoCarnet)</p>
        </div>
    </div>



        @*<div class="col-sm-3">
                <strong>@Html.LabelFor(model => model.Direccion)</strong>
                <p>@Html.DisplayFor(model => model.Direccion)</p>
            </div>
            <div class="col-sm-2">
                <strong>@Html.LabelFor(model => model.CodPostal)</strong>
                <p>@Html.DisplayFor(model => model.CodPostal)</p>
            </div>
            <div class="col-sm-2">
                <strong>@Html.LabelFor(model => model.Poblacion)</strong>
                <p>@Html.DisplayFor(model => model.Poblacion)</p>
            </div>
            <div class="col-sm-2">
                <strong>@Html.LabelFor(model => model.Provincia)</strong>
                <p>@Html.DisplayFor(model => model.Provincia)</p>
            </div>*@
</div>

    @*<div class="row">
                <div class="col-sm-2">
                    <strong>@Html.LabelFor(model => model.CECO)</strong>
                    <p>@Html.DisplayFor(model => model.CECO)</p>
                </div>
                <div class="col-sm-2">
                    <strong>@Html.LabelFor(model => model.Telefono)</strong>
                    <p>@Html.DisplayFor(model => model.Telefono)</p>
                </div>
                <div class="col-sm-2">
                    <strong>@Html.LabelFor(model => model.Movil)</strong>
                    <p>@Html.DisplayFor(model => model.Movil)</p>
                </div>

                <div class="col-sm-2">
                    <strong>@Html.LabelFor(model => model.FechaNacimiento)</strong>
                    <p>@Html.DisplayFor(model => model.FechaNacimiento)</p>
                </div>
                <div class="col-sm-2">
                    <strong>@Html.LabelFor(model => model.FechaVtoCarnet)</strong>
                    <p>@Html.DisplayFor(model => model.FechaVtoCarnet)</p>
                </div>
            </div>
        </div>*@

    @*<div id="carnet" class="tab-pane fade">
                <div class="row">
                    <div class="col-sm-5">
                            <div id="divcarnetConducir" class="embed-responsive embed-responsive-4by3">
                                <iframe  id="carnetConducir" class="embedly-embed"
                                        src='@Url.Action("GetImgCarnetConducir", "MiVehiculo", new { nombreArchivo = Model.CarnetConducir, idAlerta = Model.idAlertaCarnet })'
                                        scrolling="no" frameborder="0" allowfullscreen></iframe>
                            </div>
                    </div>
                </div>
            </div>
        </div>*@

    @if (!VerFichaConductor)
    {
        <h2>Historial de conductores</h2>
        <table id="tableconductores" class="display responsive" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>@TK_ECAR.Content.resources.ModelsResources.lblConductor</th>
                    <th>@TK_ECAR.Content.resources.ModelsResources.lblFecha</th>

                </tr>
            </thead>

            @*<tbody>
                    @foreach (var item in Model.ListaConductores)
                        {
                        <tr>
                            <td>@item.Conductor</td>
                            <td>@Html.DisplayFor(modelItem => item.Fecha)</td>
                        </tr>
                    }

                </tbody>*@
        </table>
    }

    <script type="text/javascript">

        //$(document).ready(function () {
        //    $('#tab_Conductor a[href="#fichaConductor"]').trigger('click');
        //});

    </script>

TK_ECAR/Views/MiVehiculo/_DatosMulta.cshtml
@using resourceView = TK_ECAR.Content.resources.TK_ECAR_Resource
@using TK_ECAR.Models
@model IEnumerable<DatosVehiculoMultaModel>

<h2>@resourceView.TitleListadoMultas</h2>
<table id="tabledatosmulta" class="display responsive" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>@TK_ECAR.Content.resources.ModelsResources.lblFecha</th>
            <th>@TK_ECAR.Content.resources.ModelsResources.lblImporte</th>
            <th>@TK_ECAR.Content.resources.ModelsResources.lblMotivo</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
            {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Fecha)</td>
                <td>@Html.DisplayFor(modelItem => item.Importe)</td>
                <td>@item.Motivo</td>
            </tr>
        }

    </tbody>

    @*<tbody>
            <tr>
                <td>01/01/2015</td>
                <td>10</td>
                <td>wdnflwñleñdñwed</td>
            </tr>
        }*@

    </tbody>

</table>

TK_ECAR/Views/MiVehiculo/_Documentacion.cshtml
@using resourceView = TK_ECAR.Content.resources
@using TK_ECAR.Models
@using TK_ECAR.Framework;

<div class="row">
    <div class="col-sm-12">
        <div class="info">
            @{
                var actionLink = Ajax.ActionLink("JSTITLEMODAL", "NuevoDocumentoVehiculo", "MiVehiculo", new { matricula = "valormatricula" },
                        new AjaxOptions
                        {
                            UpdateTargetId = "modalbodyDocumentacionVehiculo",
                            OnSuccess = "showModalDocumentacionVehiculo();",
                            OnComplete = "completeModal()",
                            InsertionMode = InsertionMode.Replace,
                            OnBegin = "setTitleModal('JSTITLEMODAL')",
                            HttpMethod = "POST"
                        }, new { @title = "tooltip", @class = "tk-icon-med icon-tk-plus", @style = "float: right;" }).ToString();
            }
            <span id="linkuser" style="float: right;">@resourceView.TK_ECAR_Resource.LNuevoDocumento</span>
            @Html.Raw(actionLink.Replace("JSTITLEMODAL", @resourceView.TK_ECAR_Resource.LNuevoDocumento).Replace("valormatricula", @ViewData["Matricula"].ToString()))
        </div>
        <div style="float:left; margin: 6px; border-bottom: 1px solid #ddd;" class="col-sm-12" width="100%"></div>
    </div>
</div>

<script type="text/javascript">
    $.validator.setDefaults({ ignore: null }); //para validar campos ocultos
</script>

@using (Html.BeginForm("GrabaDocumentoVehiculo", "MiVehiculo", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "stripHtml('formDocumentacionVehiculo')", @id = "formDocumentacionVehiculo" }))
{
  @Html.AntiForgeryToken()

    <input type="text" id="matricula" class="form-control" value=@ViewData["Matricula"] style="visibility:hidden" />

    <table id="tableDocumentacion" class="display responsive" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>idDocumento</th>
                <th>Documento</th>
                <th>FechaAlta</th>
                <th>IdAlerta</th>
                <th>idCategoria</th>
                <th>Matricula</th>
                <th>@TK_ECAR.Content.resources.ModelsResources.lblCategoria</th>
                <th>@TK_ECAR.Content.resources.ModelsResources.lblDescripcion</th>
                <th class="text-center">@resourceView.TK_ECAR_Resource.DataTableCabAccion</th>

            </tr>
        </thead>
    </table>

    <div class="modal fade" id="modalDocumentacionVehiculo" role="dialog">
        <div class="vertical-alignment-helper">
            <div class="modal-dialog  vertical-align-center">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                            <span class="modal-header-logo"></span>
                        </button>
                        <h4 class="modal-title" id="modaltitleDocumentacionVehiculo"> </h4>
                    </div>

                    <div class="modal-body">
                        @*<div id="toast-container"></div>*@
                        <div id="modalbodyDocumentacionVehiculo"></div>

                    </div>
                    <div class="modal-footer">
                        <button type="submit" id="btnaceptarDocumentacionVehiculo" class="btn btn-default">@resourceView.TK_ECAR_Resource.AccionAceptar</button>
                        @*<button type="button" class="btn btn-cancel" data-dismiss="modal">@resourceView.TK_ECAR_Resource.AccionCerrar</button>*@
                        <button type="button" id="btcancelarDocumentacionVehiculo" class="btn btn-cancel">@resourceView.TK_ECAR_Resource.AccionCerrar</button>
                    </div>

                </div>
            </div>
        </div>
    </div>


    @*@Html.Partial("_DocumentacionVehiculoModal")*@
}

<script type="text/javascript">
    var _tableDocumentacion;
    var uRl_DownLoadDoc;
    var uRl_DeleteDoc;
    var TipoITV = @((int)EnumTipoAlerta.ITV);

    $(document).ready(function () {

        $('#formDocumentacionVehiculo').validate({
            ignore: [],
        });

        $('#existente').hide();

        uRl_DownLoadDoc = '@Html.Raw(@Url.Action("DowmnLoadDocumentoVehiculo", "MiVehiculo", new { idDocumento = "valoriddocumento", matricula = "valormatricula", idAlerta = "valoridalerta", idCatergoria = "valoridcategoria" }))';
        uRl_DeleteDoc = '@Html.Raw(@Url.Action("BorrarDocumentoVehiculo", "MiVehiculo", new { idDocumento = "valoriddocumento", matricula = "valormatricula" }))';

        var _matricula = $("#matricula").val();

        var uRl_DataTable = '@Url.Action("DocumentacionVehiculoJson", "MiVehiculo", new {matricula = "valormatricula" })';
        uRl_DataTable = uRl_DataTable.replace("valormatricula", _matricula);

        _tableDocumentacion = $('#tableDocumentacion').DataTable({
            //"destroy": true,
            "autoWidth": false,
            "ordering": true,
            "processing": true,
            "paginate": true,
            "ajax": {
                "url": uRl_DataTable,
                "datatype": "json",
                "type": "POST"

            },
            "columns": [
                { "data": "idDocumento" },
                { "data": "Documento" },
                { "data": "FechaAlta" },
                { "data": "IdAlerta" },
                { "data": "idCategoria" },
                { "data": "Matricula" },
                { "data": "DescCategoria" },
                { "data": "DescDocumento" },
                { "data": "Accion" }
            ],
            "language": {
                "url": "//desapps.thyssenkrupp.gtk.local/TKCommon/Content/DataTables/i18n/Spanish.json"
            },
            //"data": respuesta.data,
            "columnDefs": [
            {
                "targets": [0, 1, 2, 3, 4, 5],
                "visible": false,
                "searchable": false
            },
            @*{
                "targets": 1,
                "type": "html",
                "render": function (data, type, row) {
                    var cadena = row.Documento;
                    var idalerta = row.IdAlerta;
                    if (row.idDocumento == 0) {
                        cadena = '@globalUtils.PathToUploadDocumentAlertas' + idalerta + "/" + row.Documento;
                    }
                    return cadena;
                }
            },*@
            {
                "targets": 8,
                "type": "html",
                "render": function (data, type, row) {
                    var idalerta = row.IdAlerta;
                    var cadena = "<div style='text-align: center'>";
                    cadena += '<a href="#" onclick="downloadFileMiVehiculo(' + row.idDocumento + ',\'' + row.Matricula + '\',' + row.IdAlerta  + ', ' + row.idCategoria + ')" class="tk-icon icon-tk-download"  data-toggle = "tooltip" title = "@resourceView.TK_ECAR_Resource.btnVerDoc"> </a>';
                    if (row.IdAlerta == 0 && row.idCategoria != TipoITV) {
                        cadena += '<a href="#" onclick="deleteFileMiVehiculo(' + row.idDocumento + ',\'' + row.Matricula + '\')" class="tk-icon icon-tk-delete" data-toggle = "tooltip" title = "@resourceView.TK_ECAR_Resource.TitleDocumentacionBorrar"> </a>';
                    }
                    cadena += '</div>';
                    return cadena;
                }
            }
            ]
        });

        $("#formDocumentacionVehiculo").submit(function (e) {
            if ($("#formDocumentacionVehiculo").valid()) {//validamos el form
                LimpiaValidationSummary();
                if ($("#Documento").val() != "") {
                    var formData = new FormData(this);
                    $.ajax({
                        type: this.method,
                        url: this.action,
                        data: formData,
                        contentType: false,
                        processData: false
                    }).done(function (data) {
                        doneSuccess(data);
                    });
                }
                else {
                    $("#divValidationSummaryPanel_body ul").append(textError.replace("texto", '@Html.Raw(@resourceView.ModelsResources.RequiredFile)'));
                    $('#divValidationSummary').addClass("validation-summary-errors").removeClass("validation-summary-valid");
                    $("#divValidationSummary").show();
                }
            }

            e.preventDefault();
        });

        $(document).on('click', '#btcancelarDocumentacionVehiculo', function (event) {
            $('#modalDocumentacionVehiculo').modal('hide');
        });

    });

    function doneSuccess(data) {

        if (data == "Success") {
            @*toastr["info"]("@resourceView.TK_ECAR_Resource.toastrInfDocumentoCorrecto");*@
            notify('@resourceView.TK_ECAR_Resource.toastrInfAccionOK', 'i');
            $('#modalDocumentacionVehiculo').modal('hide');
            reloadTable();
        }
        else {
            @*toastr["info"]("@resourceView.TK_ECAR_Resource.toastrInfDocumentoError");*@
            notify('@resourceView.TK_ECAR_Resource.toastrInfDocumentoError', 'i');
        }
    }

    function downloadFileMiVehiculo(idDocumento, matricula, idalerta, idcategoria) {
        var uRl = uRl_DownLoadDoc.replace("valoriddocumento", idDocumento)
                                    .replace("valormatricula", matricula)
                                    .replace("valoridalerta", idalerta)
                                    .replace("valoridcategoria", idcategoria);
        //$.ajax({
        //    type: 'POST',
        //    url: uRl,
        //    async: false,
        //    success: function (data) {
        window.location = uRl;
        //    }
        //});
    }

    function deleteFileMiVehiculo(idDocumento, matricula) {
        var uRl = uRl_DeleteDoc.replace("valoriddocumento", idDocumento).replace("valormatricula", matricula);
        confirm('@resourceView.TK_ECAR_Resource.TitleDocumentacionBorrar', '@resourceView.TK_ECAR_Resource.DocumentacionBorrar',
            function (result) {
                if (result) {
                    $.ajax({
                        type: "POST",
                        async: false,
                        url: uRl,
                        dataType: "json",
                        contentType: "application/json"
                    }).done(function (data) {
                        if (data == 'Success') {
                            @*toastr["info"]("@resourceView.TK_ECAR_Resource.toastrInfDocumentoBorradoCorrecto");*@
                            notify('@resourceView.TK_ECAR_Resource.toastrInfDocumentoBorradoCorrecto', 'i');
                            reloadTable();
                        }
                        else {
                            @*toastr["info"]("@resourceView.TK_ECAR_Resource.toastrInfDocumentoError");*@
                            notify('@resourceView.TK_ECAR_Resource.toastrInfDocumentoError', 'i');
                        }
                    });
                }
            });
    };

    function reloadTable() {
        _tableDocumentacion.ajax.reload(null, false);
        //_tableDocumentacion
        //.clear();

        //_tableDocumentacion.rows.add(data)
        //.draw();
    }


    function showModalDocumentacionVehiculo() {
        $('#modalDocumentacionVehiculo').modal('show');
    }
    function setTitleModal(title) {
        $('#modaltitleDocumentacionVehiculo').text(title);
    }

    //function completeModal() {
    //    //para que funcione los validadores a la viewpartial recien creada.
    //    //reconstruye el DOM con los validadores de los campos nuevos
    //    $("form").removeData("validator");
    //    $("form").removeData("unobtrusiveValidation");
    //    $.validator.unobtrusive.parse("form");
    //    $("form").validate();
    //}


    $("#modalDocumentacionVehiculo").on('hidden.bs.modal', function () {
        $(this).data('bs.modal', null);
    });


</script>

 

TK_ECAR/Views/MiVehiculo/_DocumentacionVehiculoAlta.cshtml
@using resourceView = TK_ECAR.Content.resources.TK_ECAR_Resource
@using TK_ECAR.Models
@model DatosVehiculoDocumentacionModel


@Html.HiddenFor(m => m.idDocumento)
@Html.HiddenFor(m => m.Matricula)
@Html.HiddenFor(m => m.Documento)
@Html.HiddenFor(m => m.Accion)
<div class="form-horizontal">
    <div class="form-group">       
        @Html.RequiredLabelFor(m => m.idCategoria, new { @class = "control-label col-sm-4" })
        <div class="col-sm-8">       
            @Html.DropDownListTiposAlertas("idCategoria", new { @class = "form-control" }, Model.idCategoria)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.DescDocumento, new { @class = "control-label col-sm-4" })
        <div class="col-sm-8">
            @Html.TextAreaFor(m => m.DescDocumento, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.RequiredLabelFor(m => m.FileUploadDocumentacion, new { @class = "control-label col-sm-4" })
        <div class="col-sm-8">
            @Html.EditorFor(m => m.FileUploadDocumentacion)
            @*@Html.TextBoxFor(m => m.Documento, new { style = "display: none;" })*@
        </div>
    </div>
    <div class="form-group" id="existente">
        <div class="col-sm-4">
        </div>
        <div class="col-sm-8">
            <div class="info">
                <h3>@Html.Raw(@resourceView.LDocumentoExistente)</h3>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-12">
            @Html.Partial("_CustomValidationSummary", ViewData.ModelState)
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function () {
        $('#existente').hide();

        //CompruebaArchivo
        $("#FileUploadDocumentacion").on('change', function (evt) {
            var _archivo = $("#FileUploadDocumentacion").val();
            var _matricula = $("#Matricula").val();
            if (_archivo != "") {
                $("#Documento").val(document.getElementById("FileUploadDocumentacion").files[0].name);
                _data = "{nombreArchivo:" + JSON.stringify(document.getElementById("FileUploadDocumentacion").files[0].name) + ", matricula:" + JSON.stringify(_matricula) + "}";
                $.ajax({
                    type: "POST",
                    async: false,
                    url: '@Url.Action("CompruebaDocumentoVehiculo", "MiVehiculo")',
                    data: _data,
                    dataType: "json",
                    contentType: "application/json",
                    success: function (res) {
                        if (res) {
                            $('#existente').show();
                        }
                        else {
                            $('#existente').hide();
                        }
                    }
                });
            }
        });
    });

</script>

 