TK_ECAR/Controllers/MtoGenericoTiposController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TK_ECAR.Application_Services;
using TK_ECAR.Content.resources;
using TK_ECAR.Framework;
using TK_ECAR.Models;

namespace TK_ECAR.Controllers
{
    public class MtoGenericoTiposController : BaseController
    {
        #region index - Sustituyo el método Index, por cada uno de los mantenimientos, para que se remarque en el menú, el que está activo.
        public ActionResult Carburante(int tipoMantenimiento)
        {
            EstableceTextosViewData(tipoMantenimiento);
            MtoGenericoTiposModels mtoGenerico = DevuelveMtoGenerico(tipoMantenimiento, EnumAccionEntity.SinAccion);

            return View("Index");
        }
        public ActionResult Marcas(int tipoMantenimiento)
        {
            EstableceTextosViewData(tipoMantenimiento);
            MtoGenericoTiposModels mtoGenerico = DevuelveMtoGenerico(tipoMantenimiento, EnumAccionEntity.SinAccion);

            return View("Index");
        }
        public ActionResult Modelos(int tipoMantenimiento)
        {
            EstableceTextosViewData(tipoMantenimiento);
            MtoGenericoTiposModels mtoGenerico = DevuelveMtoGenerico(tipoMantenimiento, EnumAccionEntity.SinAccion);

            return View("Index");
        }
        public ActionResult Ruta(int tipoMantenimiento)
        {
            EstableceTextosViewData(tipoMantenimiento);
            MtoGenericoTiposModels mtoGenerico = DevuelveMtoGenerico(tipoMantenimiento, EnumAccionEntity.SinAccion);

            return View("Index");
        }
        public ActionResult Seguro(int tipoMantenimiento)
        {
            EstableceTextosViewData(tipoMantenimiento);
            MtoGenericoTiposModels mtoGenerico = DevuelveMtoGenerico(tipoMantenimiento, EnumAccionEntity.SinAccion);

            return View("Index");
        }
        public ActionResult Ubicaciones(int tipoMantenimiento)
        {
            EstableceTextosViewData(tipoMantenimiento);
            MtoGenericoTiposModels mtoGenerico = DevuelveMtoGenerico(tipoMantenimiento, EnumAccionEntity.SinAccion);

            return View("Index");
        }

        public ActionResult TarjetaCombustible(int tipoMantenimiento)
        {
            EstableceTextosViewData(tipoMantenimiento);
            MtoGenericoTiposModels mtoGenerico = DevuelveMtoGenerico(tipoMantenimiento, EnumAccionEntity.SinAccion);

            return View("Index");
        }
        public ActionResult Vehiculos(int tipoMantenimiento)
        {
            EstableceTextosViewData(tipoMantenimiento);
            MtoGenericoTiposModels mtoGenerico = DevuelveMtoGenerico(tipoMantenimiento, EnumAccionEntity.SinAccion);

            return View("Index");
        }

        public ActionResult TipoLiquidacion(int tipoMantenimiento)
        {
            EstableceTextosViewData(tipoMantenimiento);
            MtoGenericoTiposModels mtoGenerico = DevuelveMtoGenerico(tipoMantenimiento, EnumAccionEntity.SinAccion);

            return View("Index");
        }
        #endregion
        //public ActionResult Index(int tipoMantenimiento)
        //{
        //    EstableceTextosViewData(tipoMantenimiento);
        //    MtoGenericoTiposModels mtoGenerico = DevuelveMtoGenerico(tipoMantenimiento, EnumAccionEntity.SinAccion); 

        //    return View();
        //}

        #region Mantenimiento
        public ActionResult NuevoTipoGenerico(int tipoMantenimiento)
        {

            EstableceTextosViewData(tipoMantenimiento);
            MtoGenericoTiposModels mtoGenerico = DevuelveMtoGenerico(tipoMantenimiento, EnumAccionEntity.Alta);
            mtoGenerico.TipoMtoGenerico = (EnumMtoTiposGenerales)Enum.ToObject(typeof(EnumMtoTiposGenerales), tipoMantenimiento);

            return PartialView("_MtoGenericoTipos", mtoGenerico);
        }

        public ActionResult EditarMtoGenerico(int id, int tipoMantenimiento)
        {
            EstableceTextosViewData(tipoMantenimiento);
            var mtoGenerico = new MtoTiposGeneralesService().GetMtoGeneralTiposDatatable(tipoMantenimiento,true, id).First();
            mtoGenerico.TipoMtoGenerico = (EnumMtoTiposGenerales)Enum.ToObject(typeof(EnumMtoTiposGenerales), tipoMantenimiento);

            return PartialView("_MtoGenericoTipos", mtoGenerico);
        }

        public ActionResult BorraMtoGenerico(int id, int tipoMantenimiento)
        {
            var mtoTiposGenService = new MtoTiposGeneralesService();

            var mtoGenerico = mtoTiposGenService.GetMtoGeneralTiposDatatable(tipoMantenimiento, true, id).First();
            mtoGenerico.TipoMtoGenerico = (EnumMtoTiposGenerales)Enum.ToObject(typeof(EnumMtoTiposGenerales), tipoMantenimiento);
            mtoGenerico.Baja = true;
            mtoGenerico.Accion = EnumAccionEntity.Baja;
            mtoTiposGenService.SaveMtoTipoGeneral(mtoGenerico);

            return Json("Success", JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GuardarMtoGenerico(MtoGenericoTiposModels modelo)
        {
            var mtoTiposGenService = new MtoTiposGeneralesService();

            mtoTiposGenService.SaveMtoTipoGeneral(modelo);

            return Json("Success", JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region CargaDatatable
        public ActionResult MtoGenericoJson(int tipoMantenimiento)
        {
            var mtoGenericoList = new MtoTiposGeneralesService().GetMtoGeneralTiposDatatable(tipoMantenimiento);

            var data = new
            {
                data = mtoGenericoList,
                draw = 1,
                recordsFiltered = mtoGenericoList.Count,
                recordsTotal = mtoGenericoList.Count
            };

            return Json(data, JsonRequestBehavior.AllowGet);
        }
        #endregion


        #region métodos privados
        private MtoGenericoTiposModels DevuelveMtoGenerico(int tipoMantenimiento, EnumAccionEntity accion, int id = 0)
        {
            MtoGenericoTiposModels valorReturn = new MtoGenericoTiposModels();

            valorReturn.Accion = accion;

            if (tipoMantenimiento != (int)EnumMtoTiposGenerales.Modelos)
            {
                valorReturn.ID_Tipo_FOREIGN = 0;
            }

            valorReturn.TipoMtoGenerico = (EnumMtoTiposGenerales)Enum.ToObject(typeof(EnumMtoTiposGenerales), tipoMantenimiento);

            return valorReturn;
        }

        private void EstableceTextosViewData(int tipoMantenimiento)
        {
            var _MtoGenerico = string.Empty;
            var _MtoGenericoInf = string.Empty;
            var _CabeceraMtoGenerico = string.Empty;
            var _CabeceraMtoGenericoForeign = string.Empty;
            var _BorrarMtoGenerico = string.Empty; 

            switch (tipoMantenimiento)
            {
                case (int)EnumMtoTiposGenerales.Carburante:
                    _MtoGenerico = @TK_ECAR_Resource.ResourceManager.GetString("TitleCarburante");
                    _MtoGenericoInf = @TK_ECAR_Resource.ResourceManager.GetString("TitleCarburanteInf");
                    _CabeceraMtoGenerico = @TK_ECAR_Resource.ResourceManager.GetString("CabCarburante");
                    _BorrarMtoGenerico = @TK_ECAR_Resource.ResourceManager.GetString("LBorrarCarburante"); 
                    break;
                case (int)EnumMtoTiposGenerales.Marcas:
                    _MtoGenerico = @TK_ECAR_Resource.ResourceManager.GetString("TitleMarcaVehiculo");
                    _MtoGenericoInf = @TK_ECAR_Resource.ResourceManager.GetString("TitleMarcaVehiculoInf");
                    _CabeceraMtoGenerico = @TK_ECAR_Resource.ResourceManager.GetString("CabMarcaVehiculo");
                    _BorrarMtoGenerico = @TK_ECAR_Resource.ResourceManager.GetString("LBorrarMarca");
                    break;
                case (int)EnumMtoTiposGenerales.Modelos:
                    _MtoGenerico = @TK_ECAR_Resource.ResourceManager.GetString("TitleModeloVehiculo");
                    _MtoGenericoInf = @TK_ECAR_Resource.ResourceManager.GetString("TitleModeloVehiculoInf");
                    _CabeceraMtoGenerico = @TK_ECAR_Resource.ResourceManager.GetString("CabModeloVehiculo");
                    _BorrarMtoGenerico = @TK_ECAR_Resource.ResourceManager.GetString("LBorrarModelo");
                    _CabeceraMtoGenericoForeign = @TK_ECAR_Resource.ResourceManager.GetString("CabMarcaVehiculo");
                    break;
                case (int)EnumMtoTiposGenerales.Ruta:
                    _MtoGenerico = @TK_ECAR_Resource.ResourceManager.GetString("TitleTipoRuta");
                    _MtoGenericoInf = @TK_ECAR_Resource.ResourceManager.GetString("TitleTipoRutaInf");
                    _CabeceraMtoGenerico = @TK_ECAR_Resource.ResourceManager.GetString("CabTipoRuta");
                    _BorrarMtoGenerico = @TK_ECAR_Resource.ResourceManager.GetString("LBorrarTipoRuta");
                    break;
                case (int)EnumMtoTiposGenerales.Seguro:
                    _MtoGenerico = @TK_ECAR_Resource.ResourceManager.GetString("TitleTipoSeguro");
                    _MtoGenericoInf = @TK_ECAR_Resource.ResourceManager.GetString("TitleTipoSeguroInf");
                    _CabeceraMtoGenerico = @TK_ECAR_Resource.ResourceManager.GetString("CabTipoSeguro");
                    _BorrarMtoGenerico = @TK_ECAR_Resource.ResourceManager.GetString("LBorrarTipoSeguro");
                    break;
                case (int)EnumMtoTiposGenerales.TarjetaCombustible:
                    _MtoGenerico = @TK_ECAR_Resource.ResourceManager.GetString("TitleTipoTarjetaCombustible");
                    _MtoGenericoInf = @TK_ECAR_Resource.ResourceManager.GetString("TitleTipoTarjetaCombustibleInf");
                    _CabeceraMtoGenerico = @TK_ECAR_Resource.ResourceManager.GetString("CabTipoTarjetaCombustible");

TK_ECAR/Views/MtoGenericoTipos/_ModalMtoGenericoTipos.cshtml
@using resourceView = TK_ECAR.Content.resources.TK_ECAR_Resource


@using (Html.BeginForm("GuardarMtoGenerico", "MtoGenericoTipos", null, FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "stripHtml('formMtoGenerico')", @id= "formMtoGenerico" }))
{ @Html.AntiForgeryToken()
    
        <div class="modal fade" id="modalMtoGenerico" role="dialog">
            <div class="vertical-alignment-helper">
                <div class="modal-dialog modal-md vertical-align-center">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                <span class="modal-header-logo"></span>
                            </button>
                            <h4 class="modal-title" id="modaltitleMtoGenerico"> </h4>
                        </div>
                         
                        <div class="modal-body"> 
                            @*<div id="toast-container"></div>*@              
                            <div id="modalbodyMtoGenerico"></div> 
                            
                        </div>                             
                        <div class="modal-footer">
                            <button type="submit" id="aceptarMtoGenerico" class="btn btn-default">@resourceView.AccionAceptar</button>
                            <button type="button" class="btn btn-cancel" data-dismiss="modal">@resourceView.AccionCerrar</button>
                         </div>

                    </div>
                </div>
            </div>
        </div>
}

<script type="text/javascript">

    $(document).ready(function () {
        $("#formMtoGenerico").submit(function (e) {
            if ($("#formMtoGenerico").valid()) {//validamos el form
                var formData = new FormData(this);
                @*var uRl = '@Url.Action("Index", "MtoGenericoTipos")';*@
                $.ajax({
                    type: this.method,
                    url: this.action,
                    data: formData,
                    contentType: false,
                    processData: false,

                    success: function (data) {
                        ajaxSuccessMtoGenericoTipos();
                        reloadTableMtoGenerico()
                        //setTimeout(function () { window.location.replace(uRl) }, 1000);

                    },
                    error: function (error) {
                        ajaxErrorMtoGenericoTipos();
                    }
                });
            }

            e.preventDefault();

        });

    });

    function ajaxSuccessMtoGenericoTipos() {

        notify('@resourceView.toastrInfMtoGenericoCorrecto', 'i');
        $('#modalMtoGenerico').modal('hide');
    }

    function ajaxErrorMtoGenericoTipos() {

        notify('@resourceView.toastrInfMtoGenericoError', 'e');
    }


</script>

TK_ECAR/Views/MtoGenericoTipos/_MtoGenericoTipos.cshtml
@using resourceView = TK_ECAR.Content.resources.TK_ECAR_Resource
@using TK_ECAR.Models
@using TK_ECAR.Framework
@model MtoGenericoTiposModels

@{
    var tipoMantenimiento = Convert.ToInt32(ViewData["TipoMtoGenerico"].ToString());
    var textoCabecera = ViewData["CabeceraMtoGenerico"].ToString() + "*";
}

@Html.HiddenFor(m => m.ID_Tipo)
@Html.HiddenFor(m => m.Accion)
@Html.HiddenFor(m => m.TipoMtoGenerico)
@Html.HiddenFor(m => m.TieneITV)
<div class="form-horizontal">
    @if (tipoMantenimiento == (int)EnumMtoTiposGenerales.Modelos)
    {
        <div class="form-group">
            @Html.RequiredLabelFor(m => m.ID_Tipo_FOREIGN, new { @class = "control-label col-sm-3" })
            <div class="col-sm-8">
                @Html.DropDownListMarcasVehiculo("ID_Tipo_FOREIGN", new { @class = "chosen-select" }, Model.ID_Tipo_FOREIGN)
            </div>
        </div>
    }
    else
    {
        @Html.HiddenFor(m => m.ID_Tipo_FOREIGN)
    }
    <div class="form-group">
        @Html.LabelFor(m => m.Descripcion, @textoCabecera, new { @class = "control-label col-sm-3" })
        <div class="col-sm-8">
            @Html.TextBoxFor(m => m.Descripcion, new { @class = "form-control" })
        </div>
    </div>    
    @if (tipoMantenimiento == (int)EnumMtoTiposGenerales.Vehiculos)
    {
        <div class="form-group">
            @Html.RequiredLabelFor(m => m.TieneITV, new { @class = "control-label col-sm-3" })
            <div class="col-sm-2" style="margin-left: -27px;">
                <div class="material-switch pull-right col-xm-2">
                    <input id="marcaITV" name="marcaITV" type="checkbox" />
                    <label for="marcaITV" class="label-primary"></label> @*label-default, label-primary, label-success, label-info, label-warning, label-danger*@
                </div>
            </div>
        </div>
    }

    <div class="form-group">
        <div class="col-sm-12">
            @Html.Partial("_CustomValidationSummary", ViewData.ModelState)
        </div>
    </div>

</div>

 <script type="text/javascript">
     $(document).ready(function () {
         if ($("#TieneITV").val() == "True") {
             $("#marcaITV").prop('checked', true);
         }
     });

     $(function () {
         var _tipoMto = @((int)@EnumMtoTiposGenerales.Modelos);
         if (@tipoMantenimiento == _tipoMto){
             $('.chosen-select').chosen();
             $('.chosen-select-deselect').chosen({ allow_single_deselect: true });
             $('.chosen-container').width('100%');
         }
     });

     $("#marcaITV").click(function () {
         if ($("#marcaITV").is(':checked')) {
             $("#TieneITV").val(true);
         }
         else {
             $("#TieneITV").val(false);
         }
     });
</script>