TK_ECAR/Controllers/DocumentosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TK_ECAR.Application_Services;
using TK_ECAR.Models;
using TK_ECAR.Utils;
using HelperExtensionsNameSpace;
using Newtonsoft.Json;

namespace TK_ECAR.Controllers
{
    public class DocumentosController : BaseController
    {
        public ActionResult Index()
        {
            var documentos = new DocumentacionService().AllDocumentacionDataTable();

            return View(documentos);
        }

        public ActionResult VerDocumentacion()
        {
            return View();
        }

        public ActionResult NuevoDocumento()
        {
            DocumentacionModel documentacion = new DocumentacionModel();
            documentacion.Accion = Framework.EnumAccionEntity.Alta;
            return PartialView("_MantenimientoDocumentacion", documentacion);
        }

        public ActionResult BorrarDocumento(int idDocumentacion)
        {

            DocumentacionService serviceDocumentacion = new DocumentacionService();
            var documento = serviceDocumentacion.GetDocumentacion(idDocumentacion);
            documento.Accion = Framework.EnumAccionEntity.Baja;

            return PartialView("_BorrarDocumentacion", documento);
        }

        public ActionResult EditarDocumento(int idDocumentacion)
        {

            DocumentacionService serviceDocumentacion = new DocumentacionService();
            var documento = serviceDocumentacion.GetDocumentacion(idDocumentacion);
            documento.Accion = Framework.EnumAccionEntity.Modificacion;

            return PartialView("_MantenimientoDocumentacion", documento);
        }


        [ActionName("GuardarDocumentacion")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GuardarDocumentacion(DocumentacionModel modelo)
        {
            DocumentacionService serviceDocumentacion = new DocumentacionService();

            if (modelo.Accion == Framework.EnumAccionEntity.Alta || modelo.Accion == Framework.EnumAccionEntity.Modificacion)
            {
                serviceDocumentacion.SaveDocumentacion(modelo);
            }
            else if (modelo.Accion == Framework.EnumAccionEntity.Baja)
            {
                serviceDocumentacion.DeleteDocumentacion(modelo.ID_Documento);
            }

            return Json("Success", JsonRequestBehavior.AllowGet);
        }

        #region TreeView
        public string GetJsonDataTreeviewDocumentacion()
        {
            string serializeJsonData = string.Empty;

            var categorias = new DocumentacionService().AllCategorias();

            int totalCategorias = categorias.Count();

            for (int i = 0; i < totalCategorias; i++)
            {

                var documentos = new DocumentacionService().GetDocumentacionPorCategoria(new List<int?> { categorias[i].ID_Categoria });

                int totalDocumentos = documentos.Count();
                if (totalDocumentos == 0)
                {
                    ParentWithNoChild single = new ParentWithNoChild();
                    single.text = categorias[i].Nombre;
                    single.id = categorias[i].ID_Categoria;
                    serializeJsonData = serializeJsonData.MergeJsonString(JsonConvert.SerializeObject(single));
                }
                else if (totalDocumentos >= 1)
                {
                    ParentWithChildren parentCategoria = new ParentWithChildren();
                    Child[] childrenCategoria = new Child[totalDocumentos];

                    parentCategoria.text = categorias[i].Nombre;
                    parentCategoria.id = categorias[i].ID_Categoria;
                    for (int j = 0; j < totalDocumentos; j++)
                    {
                        if (!String.IsNullOrEmpty(documentos[j].Nombre))
                        {
                            Child child = new Child { text = documentos[j].Nombre, id = documentos[j].ID_Documento };
                            Child[] childrenDocumento = new Child[1];
                            Child childDocumento = new Child { text = "Descripción: " + (string.IsNullOrEmpty(documentos[j].Descripcion) ? "(Sin descripción)" : documentos[j].Descripcion) };
                            childrenDocumento[0] = childDocumento;
                            child.nodes = childrenDocumento;
                            childrenCategoria[j] = child;
                        }
                    }
                    parentCategoria.nodes = childrenCategoria;
                    serializeJsonData = serializeJsonData.MergeJsonString(JsonConvert.SerializeObject(parentCategoria));
                }
            }
            return serializeJsonData.GetTreeViewJsonFormat();
        }
        #endregion


        public ActionResult CompruebaArchivo(string nombreArchivo, int idDocumento, Framework.EnumAccionEntity accion)
        {
            bool valorReturn = false;
            DocumentacionService serviceDocumentacion = new DocumentacionService();

            if (accion == Framework.EnumAccionEntity.Alta)
            {
                valorReturn = FileUtilities.ExisteDocumentoToUploadEnDisco(Global.PathToUploadDocument + nombreArchivo);
            }
            else
            {
                valorReturn = serviceDocumentacion.ExisteDocumentoToUploadEnBBDD(idDocumento, nombreArchivo);
            }

            //System.IO.File.Exists(Global.PathToUploadDocument + nombreArchivo)
            
            return Json(valorReturn, JsonRequestBehavior.AllowGet);
        }
        

        public FileResult VerDocumento(int idDocumento)
        {
            var documentos = new DocumentacionService().GetDocumentacion(idDocumento);

            //byte[] fileBytes = System.IO.File.ReadAllBytes(@documentos.Ruta);

            var documento = Global.PathToUploadDocument + documentos.Documento;
            return File(System.Web.HttpContext.Current.Server.MapPath(documento), System.Net.Mime.MediaTypeNames.Application.Octet, Path.GetFileName(System.Web.HttpContext.Current.Server.MapPath(documento)));
        }

    }
}

TK_ECAR/Views/Documentos/Index.cshtml
@using resourceView = TK_ECAR.Content.resources.TK_ECAR_Resource
@model IEnumerable<TK_ECAR.Models.DocumentacionDataTableModel>
@using System.Configuration;

<div class="row">
    <div class="col-sm-12">
        <div class="infoDocGestion">
            @{
                var actionLink = Ajax.ActionLink("JSTITLEMODAL", "NuevoDocumento", "Documentos", new { },
                new AjaxOptions
                {
                    UpdateTargetId = "modalbodyDocumentacion",
                    OnSuccess = "showModalDocumentacion();",
                    OnComplete = "completeModal()",
                    InsertionMode = InsertionMode.Replace,
                    OnBegin = "setTitleModal('JSTITLEMODAL')"
                }, new { @title = "tooltip", @class = "tk-icon-med icon-tk-plus", @style = "float: right;" }).ToString();
            }
            @*<h3>@resourceView.TitleDocumentos    @Html.Raw(actionLink.Replace("JSTITLEMODAL", @resourceView.LNuevoDocumento))</h3>*@
            <h3>@resourceView.TitleDocumentos
                <span id="linkuser" style="float: right;">@resourceView.LAñadir</span> 
                @Html.Raw(actionLink.Replace("JSTITLEMODAL", @resourceView.LNuevoDocumento).Replace("tooltip", @resourceView.LNuevoDocumento))
            </h3>
            <p>@resourceView.TitleDocumentosInf</p>
        </div>
    </div>
</div>

@{
    var actionLinkEdit = Ajax.ActionLink("JSTITLEACTION", "EditarDocumento", "Documentos", new { idDocumentacion = "JSVARTIPO" },
    new AjaxOptions
    {
        UpdateTargetId = "modalbodyDocumentacion",
        OnSuccess = "showModalDocumentacion();",
        OnComplete = "completeModal()",
        InsertionMode = InsertionMode.Replace,
        OnBegin = "setTitleModal('JSTITLEMODAL')"
    }, new { @data_toggle = "popover", @data_placement = "top", @data_trigger = "hover", @data_content = "accionmenu" }).ToString();
    actionLinkEdit = "<a class='tk-icon-med icon-tk-edit tk-icon-bold ' "
                + actionLinkEdit.Replace("textoQuitarPorVacio", "").Replace("accionmenu", @resourceView.AccionEditar)
                 + " </a>"; 

    var actionLinkDelete = Ajax.ActionLink("JSTITLEACTION", "BorrarDocumento", "Documentos", new { idDocumentacion = "JSVARTIPO" },
    new AjaxOptions
    {
        UpdateTargetId = "modalbodyDocumentacion",
        OnSuccess = "showModalDocumentacion();",
        OnComplete = "completeModal()",
        InsertionMode = InsertionMode.Replace,
        OnBegin = "setTitleModal('JSTITLEMODAL')"
    }, new { @data_toggle = "popover", @data_placement = "top", @data_trigger = "hover", @data_content = "accionmenu" }).ToString();
    actionLinkDelete = "<a class='tk-icon-med icon-tk-delete tk-icon-bold tk-icon-red ' "
                + actionLinkDelete.Replace("textoQuitarPorVacio", "").Replace("accionmenu", @resourceView.AccionBorrar)
                 + " </a>"; 

}

<table id="tableDocumentacion" class="display responsive" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th></th>
            <th>Ordenacion</th>
            <th>ID_Categoria</th>
            <th>ID_Documento</th>
            <th>Documento</th>
            <th>@resourceView.GeneralCabCategoria</th>
            <th>@resourceView.DocumentoCabNombreDoc</th>
            <th>@resourceView.DataTableCabAccion</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
            {
            <tr>
                <td>
                    <img src="Content/img/Application/details_open.png" rel="@item.Descripcion" alt="expand/collapse">                    
                </td>
                <td>@item.Ordenacion</td>
                <td>@item.ID_Categoria</td>
                <td>@item.ID_Documento</td>
                <td>@item.Documento</td>
                <td>@item.DescCategoria</td>
                <td>@item.Nombre</td>
                <td>
                    <span></span> @Html.Raw(actionLinkEdit.Replace("JSVARTIPO", (item.ID_Documento).ToString()).Replace("JSTITLEACTION", @resourceView.AccionEditar).Replace("JSTITLEMODAL", @resourceView.TitleDocumentacionEditar))
                    @Html.Raw(actionLinkDelete.Replace("JSVARTIPO", (item.ID_Documento).ToString()).Replace("JSTITLEACTION", @resourceView.AccionBorrar).Replace("JSTITLEMODAL", @resourceView.TitleDocumentacionBorrar))
                </td>
            </tr>
        }
    </tbody>

</table>

@Html.Partial("_ModalDocumentacion")


<style>
    .export-btn {
        margin: 10px;
        padding: 5px;
    }
</style>

@section Scripts {


    <link rel="stylesheet" type="text/css" href='@Styles.Url("~/Content/dataTablecss")'>
    <link rel="stylesheet" type="text/css" href='@Styles.Url("~/Content/dataTablecssResponsive")'>
    <link rel="stylesheet" type="text/css" href='@Styles.Url("~/Content/datepicker")'>

    <script src='@Scripts.Url("~/bundles/moment")'> </script>
    <script src='@Scripts.Url("~/bundles/datatable")'> </script>
    <script src='@Scripts.Url("~/bundles/dtresponsive")'> </script>

    <script src='@Scripts.Url("~/bundles/jqueryUnobtrusiveAjax")'> </script>
    <script src='@Scripts.Url("~/bundles/jQueryValidate")'> </script>
    <script src='@Scripts.Url("~/bundles/jQueryValidateGlobal")'> </script>
    <script src='@Scripts.Url("~/bundles/jQueryValidateUnotrusive")'> </script>

    <script src='@Scripts.Url("~/bundles/DataTablesButtonJs")'> </script>
    <script src='@Scripts.Url("~/bundles/DataTablesbuttonsFlashJs")'> </script>
    <script src='@Scripts.Url("~/bundles/DataTablesbuttonsHtml5Js")'> </script>
    <script src='@Scripts.Url("~/bundles/DataTablesjszipJs")'> </script>
    <script src='@Scripts.Url("~/bundles/DataTablesVfsFontsJs")'> </script>
    
    <script type="text/javascript">
        var _tableDocumentacion;

        $(document).ready(function () {

            _tableDocumentacion = $('#tableDocumentacion').dataTable(
                {
                    responsive: {
                        details: {
                            type: 'column',
                            target: 'tr'
                        }
                    },
                    "dom": 'Blfrtip',
                    "ordering": true,
                    "processing": true,
                    "paginate": true,
                    "order": [[1, "asc"]],
                    "order": [[3, "asc"], [4, "asc"]], "buttons": [{
                        text: '@resourceView.btnExportarExcel',
                        extend: 'excel',
                        className: 'btn btn-default export-btn',
                        title: '@Html.Raw(@resourceView.TitleDocumentos)',
                        exportOptions: {
                            columns: [4, 5, 6]
                        }
                    }],
                    "language": {
                        "url": '@Url.Content(ConfigurationManager.AppSettings["baseUrl"] + "/Content/DataTables/i18n/" + @resourceView.ArchivoIdiomaDataTable )'
                    },
                    "drawCallback": function () {
                        $('[data-toggle="popover"]').popover({ html: true });
                    },
                    "columnDefs": [
                    {
                        "targets": [1, 2, 3, 4],
                        "visible": false,
                        "orderable": false,
                        "searchable": false
                        //,
                        //"mRender": function ( data, type, row ) {
                        //    return '<img src="/Content/img/Application/details_open.png" rel="' + row.Respuesta + '" alt="expand/collapse">';}
                    },
                    {
                        "targets": [0],
                        "orderable": false,
                        "searchable": false
                    }
                    ]
                });


            $('#tableDocumentacion tbody td img').click(function () {
                var nTr = $(this).parents('tr')[0];
                if (this.src.match('details_close')) {
                    this.src = "Content/img/Application/details_open.png";
                    _tableDocumentacion.fnClose(nTr);
                }
                else {
                    this.src = "Content/img/Application/details_close.png";
                    var descripcion = $(this).attr("rel");
                    _tableDocumentacion.fnOpen(nTr, fnFormatDetails(descripcion, nTr), 'details');
                }
            });
        });

        function fnFormatDetails(descripcion) {
            var sOut = '<table class="display responsive" cellpadding="5" class border="0" style="padding-left:50px;">';
            sOut += '<tr><td><span class="label label-success">@resourceView.DocumentoCabDescripcion:</span></td><td>' + descripcion + '</td></tr>';
            sOut += '</table>';
            return sOut;
        }

        function showModalDocumentacion() {
            $('#modalDocumentacion').modal('show');
        }
        function setTitleModal(title) {
            $('#modaltitleDocumentacion').text(title);
        }

        //function completeModal() {
        //    //para que funcione los validadores a la viewpartial recien creada.
        //    //reconstruye el DOM con los validadores de los campos nuevos
        //    $("form").removeData("validator");
        //    $("form").removeData("unobtrusiveValidation");
        //    $.validator.unobtrusive.parse("form");
        //    $("form").validate();
        //}

    </script>
}

TK_ECAR/Views/Documentos/VerDocumentacion.cshtml
@using resourceView = TK_ECAR.Content.resources.TK_ECAR_Resource

<div class="row">
    <div class="col-sm-12">
        <div class="infoDoc">
            <h3>@resourceView.TitleDocumentos</h3>
            <p>@resourceView.TitleDocumentosInf</p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <label for="input-search" class="sr-only">@resourceView.btnFiltroBuscar:</label>
            <input type="input" class="form-control" id="input-search" placeholder=@resourceView.btnBuscarDoc value="">
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-9">
        <div class="form-group">
            <button type="submit" id="cerrarTodosLosNodos" class="btn btn-default">@resourceView.btnCerrarNodos</button>
            <button type="submit" id="abrirTodosLosNodos" class="btn btn-default">@resourceView.btnAbrirNodos</button>
        </div>
    </div>
    <div class="col-sm-3">
        <div class="form-group" style="float: right;">
            <button type="submit" id="verDocumento" class="btn btn-default">@resourceView.btnVerDoc</button>
        </div>
    </div>
</div>


<div id="tree">

</div>
  


@section Scripts {


<link rel="stylesheet" type="text/css" href='@Styles.Url("~/bootstrapTreeviewCSSCdnPath")'>
<script src='@Scripts.Url("~/bootstrapTreeviewCdnPath")'> </script>

    <script type="text/javascript">
        //{
        //    text: "Node 1",
        //    icon: "glyphicon glyphicon-stop",
        //    selectedIcon: "glyphicon glyphicon-stop",
        //    color: "#000000",
        //    backColor: "#FFFFFF",
        //    href: "#node-1",
        //    selectable: true,
        //    state: {
        //        checked: true,
        //        disabled: true,
        //        expanded: true,
        //        selected: true
        //    },
        //    tags: ['available'],
        //    nodes: [
        //      {},
        //      ...
        //      ]
        //}

        //var data = [
        //  {
        //      text: "Categoria 1",
        //      tags: ['2'],
        //      nodes: [
        //        {
        //            text: "Documento 1",
        //            icon: "tk-icon icon-tk-document",
        //        },
        //        {
        //            text: "Documento 2",
        //            icon: "tk-icon icon-tk-document",
        //            href: "Documento2",
        //        }
        //      ]
        //  }, {
        //      text: "Categoria 2",
        //      tags: ['3'],
        //        nodes: [
        //        {
        //            text: "Documento 3",
        //            icon: "tk-icon icon-tk-document",
        //        },
        //        {
        //            text: "Documento 4",
        //            icon: "tk-icon icon-tk-document",
        //        }, {
        //            text: "Documento 5",
        //            icon: "tk-icon icon-tk-document",
        //        },
        //        ]
        //  },
        //    {
        //        text: "Categoria 3",
        //        tags: ['1'],
        //      nodes: [
        //      {
        //          text: "Documento 6",
        //          icon: "tk-icon icon-tk-document",
        //      }]
        //    },
        //    {
        //        text: "Categoria 4",
        //        tags: ['1'],
        //        nodes: [
        //        {
        //            text: "Documento 7",
        //            icon: "tk-icon icon-tk-document",
        //        }]
        //    },
        //    {
        //        text: "Categoria 5",
        //        tags: ['1'],
        //        nodes: [
        //        {
        //            text: "Documento 8",
        //            icon: "tk-icon icon-tk-document",
        //        }]
        //    }
        //];


        var _Data;
        var TreeViewDocumentos;
        var documento;

        //https://github.com/jonmiles/bootstrap-treeview
        $(document).ready(function () {
            loadUrl = '@Url.Action("GetJsonDataTreeviewDocumentacion", "Documentos")';
            verDocumentodUrl = '@Url.Action("VerDocumento", "Documentos", new { idDocumento = "valoriddocumento" })';

            $('#verDocumento').hide("fast");

            $.ajax({
                type: 'GET',
                url: loadUrl,
                async: false,
                dataType: 'json',
                success: function (data) {
                    _Data = jQuery.parseJSON(JSON.stringify(data));
                }
            });

            $TreeViewDocumentos = $('#tree').treeview({
            });

            $TreeViewDocumentos.treeview({
                data: _Data,
                showTags: true,
                multiSelect: false,
                onNodeSelected: function (event, node) {
                    if (node.parentId != null)
                    {
                        if (node.id != 0) {
                            $('#verDocumento').show("fast");
                            documento = node.id;
                        }
                        else {
                            $('#verDocumento').hide("fast");
                            documento = "";
                        }
                    }
                },
                onNodeUnselected: function (event, node) {
                    $('#verDocumento').hide("fast");
                    documento = "";
                }
            });


            $TreeViewDocumentos.treeview('collapseAll');

        });

        //******** Acciones en treeView
        //Buscar en treeView
        var search = function (e) {
            var pattern = $('#input-search').val();
            var options = {
                ignoreCase: true,
                exactMatch: false,
                revealResults: true
            };
            var results = $TreeViewDocumentos.treeview('search', [pattern, options]);

            //var output = '<p>' + results.length + ' matches found</p>';
            //$.each(results, function (index, result) {
            //    output += '<p>- ' + result.text + '</p>';
            //});
            //$('#search-output').html(output);
        }

        $('#btn-search').on('click', search);
        $('#input-search').on('keyup', search);

        $('#btn-clear-search').on('click', function (e) {
            $TreeViewDocumentos.treeview('clearSearch');
            $('#input-search').val('');
            $('#search-output').html('');
        });

        //Cerrar todos los nodos
        $('#cerrarTodosLosNodos').on('click', function (e) {
            $TreeViewDocumentos.treeview('collapseAll', { silent: true });
        });

        //Abrir todos los nodos
        $('#abrirTodosLosNodos').on('click', function (e) {
            var levels = $('#select-expand-all-levels').val();
            $TreeViewDocumentos.treeview('expandAll', { levels: levels, silent: true });
        });

        $('#verDocumento').on('click', function (e) {
            //$.ajax({
            //    type: 'POST',
            //    url: verDocumentodUrl.replace("valoriddocumento", documento),
            //    async: false,
            //    success: function (data) {
                    window.location = verDocumentodUrl.replace("valoriddocumento", documento);
            //    }
            //});
        });


    </script>
}

TK_ECAR/Views/Documentos/_BorrarDocumentacion.cshtml
@using TK_ECAR.Models
@model DocumentacionModel

@Html.HiddenFor(m => m.ID_Documento)
@Html.HiddenFor(m => m.Documento)
@Html.HiddenFor(m => m.Accion)
<div class="form-horizontal">
    <div class="form-group">
        @Html.RequiredLabelFor(m => m.ID_Categoria, new { @class = "control-label col-sm-3" })
        <div class="col-sm-8">
            @Html.DropDownListTiposCategorias("ID_Categoria", new { @class = "form-control", @disabled = "disabled" }, Model.ID_Categoria)
        </div>
    </div>

    <div class="form-group">
        @Html.RequiredLabelFor(m => m.Nombre, new { @class = "control-label col-sm-3" })
        <div class="col-sm-8">
            @Html.TextBoxFor(m => m.Nombre, new { @class = "form-control", @readonly = true })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Descripcion, new { @class = "control-label col-sm-3" })
        <div class="col-sm-8">
            @Html.TextAreaFor(m => m.Descripcion, new { @class = "form-control", @readonly = true })
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-12">
            @Html.Partial("_CustomValidationSummary", ViewData.ModelState)
        </div>
    </div>
</div>

 

TK_ECAR/Views/Documentos/_MantenimientoDocumentacion.cshtml
@using resourceView = TK_ECAR.Content.resources.TK_ECAR_Resource
@using TK_ECAR.Models
@model DocumentacionModel


@Html.HiddenFor(m => m.ID_Documento)
@Html.HiddenFor(m => m.Accion)
@Html.HiddenFor(m => m.FileUploadDocumentacion_download)
<div class="form-horizontal">
    <div class="form-group">       
        @Html.RequiredLabelFor(m => m.ID_Categoria, new { @class = "control-label col-sm-4" })
        <div class="col-sm-8">       
            @Html.DropDownListTiposCategorias("ID_Categoria", new { @class = "form-control" }, Model.ID_Categoria)
        </div>
    </div>

    <div class="form-group">
        @Html.RequiredLabelFor(m => m.Nombre, new { @class = "control-label col-sm-4" })
        <div class="col-sm-8">
            @Html.TextBoxFor(m=>m.Nombre, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Descripcion, new { @class = "control-label col-sm-4" })
        <div class="col-sm-8">
            @Html.TextAreaFor(m => m.Descripcion, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.RequiredLabelFor(m => m.FileUploadDocumentacion, new { @class = "control-label col-sm-4" })
        <div class="col-sm-8">
            @Html.EditorFor(m => m.FileUploadDocumentacion)
            @Html.TextBoxFor(m => m.Documento, new { style = "display: none;" })
        </div>
    </div>
    <div class="form-group" id="existente">
        <div class="col-sm-4">
        </div>
        <div class="col-sm-8">
            <div class="info">
                <h3>@Html.Raw(@resourceView.LDocumentoExistente)</h3>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-12">
            @Html.Partial("_CustomValidationSummary", ViewData.ModelState)
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function () {
        $('#existente').hide();

        //CompruebaArchivo
        $("#FileUpload").on('change', function (evt) {
            
            var _archivo = $("#FileUpload").val();
            var _accion = $("#Accion").val();
            var _idDocumento = $("#ID_Documento").val();
            if (_archivo != "") {
                $("#Documento").val(document.getElementById("FileUpload").files[0].name);
                _data = "{nombreArchivo:" + JSON.stringify(document.getElementById("FileUpload").files[0].name) + ", idDocumento:" + JSON.stringify(_idDocumento) + ", accion:" + JSON.stringify(_accion) + "}";
                $.ajax({
                    type: "POST",
                    async: false,
                    url: '@Url.Action("CompruebaArchivo", "Documentos")',
                    data: _data,
                    dataType: "json",
                    contentType: "application/json",
                    success: function (res) {
                        if (res) {
                            $('#existente').show();
                        }
                        else {
                            $('#existente').hide();
                        }
                    }
                });
            }
        });
    });

</script>

 

TK_ECAR/Views/Documentos/_ModalDocumentacion.cshtml
@using resourceView = TK_ECAR.Content.resources

@using (Html.BeginForm("GuardarDocumentacion", "Documentos", null, FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "stripHtml('formDocumentacion')", @id= "formDocumentacion" }))
{ @Html.AntiForgeryToken()
    
        <div class="modal fade" id="modalDocumentacion" role="dialog">
            <div class="vertical-alignment-helper">
                <div class="modal-dialog  vertical-align-center">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                <span class="modal-header-logo"></span>
                            </button>
                            <h4 class="modal-title" id="modaltitleDocumentacion"> </h4>
                        </div>
                         
                        <div class="modal-body"> 
                            @*<div id="toast-container"></div>*@              
                            <div id="modalbodyDocumentacion"></div> 
                            
                        </div>                             
                        <div class="modal-footer">
                            <button type="submit" id="aceptarDocumentacion" class="btn btn-default">@resourceView.TK_ECAR_Resource.AccionAceptar</button>
                            <button type="button" class="btn btn-cancel" data-dismiss="modal">@resourceView.TK_ECAR_Resource.AccionCerrar</button>
                         </div>

                    </div>
                </div>
            </div>
        </div>
      
}

<script type="text/javascript">
    var textError = '<li>texto</li>';

    $(document).ready(function () {
        $("#formDocumentacion").submit(function (e) {
            if ($("#formDocumentacion").valid()) {//validamos el form
                LimpiaValidationSummary();
                if ($("#FileUploadDocumentacion_download").val() != "") {
                    var formData = new FormData(this);
                    var uRl = '@Url.Action("Index", "Documentos")';
                    $.ajax({
                        type: this.method,
                        url: this.action,
                        data: formData,
                        contentType: false,
                        processData: false,

                        success: function (data) {
                            ajaxSuccessDocumentacion();
                            setTimeout(function () { window.location.replace(uRl) }, 1000);
                        },
                        error: function (error) {
                            ajaxErrorDocumentacion();
                        }
                    });
                }
                else {
                    $("#divValidationSummaryPanel_body ul").append(textError.replace("texto", '@Html.Raw(@resourceView.ModelsResources.RequiredFile)'));
                    $('#divValidationSummary').addClass("validation-summary-errors").removeClass("validation-summary-valid");
                    $("#divValidationSummary").show();
                }
            }

            e.preventDefault();

        });
    });


    function ajaxSuccessDocumentacion() {

        @*toastr["info"]("@resourceView.toastrInfDocumentoCorrecto");*@
        notify('@resourceView.TK_ECAR_Resource.toastrInfAccionOK', 'i');

        $('#modalDocumentacion').modal('hide');
    }
    function ajaxErrorDocumentacion() {

        @*toastr["error"]("@resourceView.toastrInfDocumentoError");*@
        notify('@resourceView.TK_ECAR_Resource.toastrInfDocumentoError', 'e');
    }


</script>